### ISSUE TITLE
Tutorial: How to create periodograms and identify significant peaks?

### ISSUE THREAD

**Issue by ojhall94** [barentsen/notebooks#11]
This notebook will form part of the series: Science Examples - Stellar Physics.

In this first notebook, we will focus on downloading a light curve and converting it to a periodogram. I'll keep it relatively simple, and focus on the properties of the frequency domain, which may be new to many users.

We can draw inspiration from existing Lightkurve tutorials:

- [What are periodogram objects?](http://docs.lightkurve.org/tutorials/01-using-the-periodogram-class.html)
- [How to improve the signal-to-noise of Periodograms?](http://docs.lightkurve.org/tutorials/02-how-to-optimize-periodogram-snr.html)
- [How to characterise a Sun-like star using asteroseismology?](http://docs.lightkurve.org/tutorials/02-asteroseismology.html)

I think its worth our time to work on a `periodogram` focused introductory tutorial that follows the style of the other tutorials in this series more closely, so that it becomes a bit more pedagogical, where the lightkurve tutorials are more focused on Lightkurve's capabilities specifically.

---

Learning Goals:
- What is a the frequency domain?
- What is a periodogram?
- How to make a periodogram from Kepler data
- How to interpret a Kepler periodogram

**Comment by barentsen** [comment]
:+1:

**Comment by ojhall94** [comment]
This one's ready to be looked at I think!

**Comment by barentsen** [comment]
Thanks so much for this great tutorial @ojhall.

We recently decided to remove the "Defining terms" sections from the notebooks. (I can't remember if you were on the telecon when we made that decision.)   To aid final copy-editing, I went ahead and wove some of the excellent explanations that existed in the Glossary into the tutorial content. I did this for *aliasing*, *nyquist frequency*, and *eclipsing binaries*.

I also made sure the "Additional resources" section did not contain key information that should be woven into the main content, and removed that section as well per our new template.

Other than that, I believe this notebook is ready for copy editing!

**Comment by barentsen** [comment]
The file name is `How-to-create-periodograms-and-identify-significant-peaks.ipynb`.

**Comment by lglattly** [comment]
@ojhall94 and @barentsen I finished copy editing this tutorial and it was in great shape! As per the template, I combined the summary into the Introduction section, reordered the first few sections, and then made small copy editing changes throughout. This one is all set on my end and ready to go!

**Comment by barentsen** [comment]
Thanks everyone! 👍 1:

**Comment by barentsen** [comment]
This notebook has successfully been merged into `spacetelescope/notebooks`.  Thanks everyone!  Closing the issue...
