### ISSUE TITLE
Tutorial: How to measure and remove a rotation period signal from Kepler data?

### ISSUE THREAD

**Issue by ojhall94** [barentsen/notebooks#12]
This notebook will form part of the series: Science Examples - Stellar Physics.

In this second notebook, we will focus on doing more data-analysis style work with a Kepler periodogram.

We can draw inspiration from existing Lightkurve tutorials:

- [What are periodogram objects?](http://docs.lightkurve.org/tutorials/01-using-the-periodogram-class.html)
- [How to improve the signal-to-noise of Periodograms?](http://docs.lightkurve.org/tutorials/02-how-to-optimize-periodogram-snr.html)
- [How to characterise a Sun-like star using asteroseismology?](http://docs.lightkurve.org/tutorials/02-asteroseismology.html)

--- 
Learning Goals:

- How does a Lomb-Scargle periodogram work (roughly)?
- How do I extract a frequency model from a Lomb-Scargle periodogram?
- How can I use this for a science example?

**Help needed:** I'm not super familiar with doing anything with periodograms other than asteroseismic analysis. Does anybody have any ideas for the kind of science that a LombScargle frequency model is used for?

**Comment by barentsen** [comment]
@ojhall94 For a different example, you can show the periodogram for a star with a rotation period.  There's plenty of those!  (e.g. catalog here: https://arxiv.org/abs/1402.5694 )

**Comment by ojhall94** [comment]
Hey everyone,

I've drawn up a quick draft of this notebook just using what I know. I have no idea if this is the best use of a Lomb Scargle model (I think Christina Hedges will probably know better), but hopefully I've added enough disclaimers for people to take my expertise with a pinch of salt :)

**Comment by barentsen** [comment]
I propose changing the title of this notebook from
    `How to extract and fit periodic signals`
into
    `How to measure and remove a rotation period signal from a Kepler light curve`.  It makes it a bit more specific!  Any objections?

**Comment by barentsen** [comment]
Thanks again @ojhall94!!

I carried out a final review and made a few minor changes, including:
* Bringing the contents in line with the new template.
* Editing the section titles to be more descriptive of the contents.
* Slightly rewording a few sections for clarity.

Please do let me know if I did any harm.  Otherwise, I believe this notebook is ready for copy-editing!

I changed the filename to `how-to-measure-and-remove-a-rotation-period.ipynb`.

**Comment by lglattly** [comment]
@ojhall94 and @barentsen I finished copy editing this tutorial and it was also in great shape! I made small copy editing changes throughout, incorporated the references listed at the end into the main text, and made sure the sections all matched our template. This one is all set on my end and ready to go!

**Comment by barentsen** [comment]
Thanks @lglattly!

**Comment by barentsen** [comment]
This notebook has successfully been merged into `spacetelescope/notebooks`.  Thanks everyone!  Closing the issue...
