### ISSUE TITLE
Tutorial: How to understand and manipulate a periodogram of an oscillating star

### ISSUE THREAD

**Issue by ojhall94** [barentsen/notebooks#13]
This notebook will form part of the series: Science Examples - Stellar Physics.

In this third notebook, we will focus on understanding the properties of the spectrum of a solar-like oscillator, and how to manipulate the spectrum using LIghtkurve's function key words to better study modes of oscillation.

I figured this was best to be a separate notebook to #11, which can then be more general.

We can draw inspiration from existing Lightkurve tutorials:

- [What are periodogram objects?](http://docs.lightkurve.org/tutorials/01-using-the-periodogram-class.html)
- [How to improve the signal-to-noise of Periodograms?](http://docs.lightkurve.org/tutorials/02-how-to-optimize-periodogram-snr.html)
- [How to characterise a Sun-like star using asteroseismology?](http://docs.lightkurve.org/tutorials/02-asteroseismology.html)

As well as from tutorials I made for the KASC12/TASC5 conference in 2019:
- [Rudy (Kepler) Example](https://github.com/ojhall94/TASC5_lightkurve/blob/master/Notebooks/Rudy-example.ipynb)
- [TESS Example](https://github.com/ojhall94/TASC5_lightkurve/blob/master/Notebooks/TESS-example.ipynb)
- [K2 Example](https://github.com/ojhall94/TASC5_lightkurve/blob/master/Notebooks/K2-example.ipynb)

---
Learning Goals:
- What are the key features of the periodogram of a solar-like oscillator?
- How does the periodogram change depending on what star you look at?
- How can I manipulate the periodogram to focus on the areas I'm interested in?
- How can I smooth the periodogram and remove features such as the background?

**Comment by ojhall94** [comment]
Instead of just focusing on solar-like oscillators, I was thinking of including an example of a Delta Scuti in here as well. Does anybody here know of a good benchmark star with clear oscillations? (@astrobel?)

**Comment by barentsen** [comment]
I recommend finding an example from a Delta Scuti paper, so you can check that our results match those in the paper!

For what it's worth, the five most-cited Kepler papers that contain the word Delta Scuti in the title are:

2011Natur.477..570A
2015MNRAS.452.3073B
2015AJ....149...68B
2016ApJ...826...69G
2017ApJ...837..114G

**Comment by astrobel** [comment]
Of the above papers, I would recommend the first one in particular, as it focuses on one well-known star with clear pulsation modes. The star in question also been followed up on in Bedding et al. 2020 (2020Natur.581..147B), who update the value of the large separation, so it's worth having a read of both.

**Comment by ojhall94** [comment]
I wrote an Astrobite on Bedding+2020, so I'm familiar with that star in particular. That'll be a great place to start, thank you!

**Comment by barentsen** [comment]
I have started my final review of this tutorial.

**Comment by barentsen** [comment]
I completed my review and edited the text in a few places where I felt it helped the clarity.

This notebook is ready for copy editing!  Thanks Oli!

The filename is `How_to_understand_and_manipulate_the_periodogram_of_an_oscillating_star.ipynb`.

**Comment by lglattly** [comment]
@ojhall94 and @barentsen I finished copy editing this tutorial and it was in great shape! I made minor copy edits throughout, and it is all set on my end now. Thanks!

**Comment by barentsen** [comment]
This notebook has successfully been merged into `spacetelescope/notebooks`.  Thanks everyone!  Closing the issue...
