### ISSUE TITLE
Tutorial: How to infer stellar parameters from periodograms using asteroseismology?

### ISSUE THREAD

**Issue by ojhall94** [barentsen/notebooks#14]
This notebook will form part of the series: Science Examples - Stellar Physics.

In this fourth notebook, we will focus on the asteroseismic capabilities of Lightkurve contained in the `seismology` sub-module. The user will have already learned how to prepare data foru se in this sub-module in Tutorial #13.

I wrote a lot of this up in my PhD thesis, so there is alot of material that we can use in this tutorial without having to reinvent the wheel.

We can draw inspiration from existing Lightkurve tutorials, and tutorials written for the TASC5 conference:
- [How to characterise a Sun-like star using asteroseismology?](http://docs.lightkurve.org/tutorials/02-asteroseismology.html)
- [Rudy (Kepler) Example](https://github.com/ojhall94/TASC5_lightkurve/blob/master/Notebooks/Rudy-example.ipynb)
- [TESS Example](https://github.com/ojhall94/TASC5_lightkurve/blob/master/Notebooks/TESS-example.ipynb)
- [K2 Example](https://github.com/ojhall94/TASC5_lightkurve/blob/master/Notebooks/K2-example.ipynb)

--- 
Learning Goals:
- How can we use the 2D ACF method to estimate numax and deltanu?
- What are the seismic scaling relations?
- How do we calculate stellar parameters using Lightkurve and asteroseismology?

**Comment by barentsen** [comment]
Love it! :+1:

**Comment by barentsen** [comment]
I propose naming this tutorial
`How to estimate a star's mass and radius using asteroseismology`
instead of
`How to infer stellar parameters from periodograms using asteroseismology?`
to make it sound more catchy!

**Comment by barentsen** [comment]
I completed my review of this notebook.

I did not make fundamental changes, but did take the liberty to attempt to clarify the phrasing in a few places.

The file name is `How-to-Estimate-a-Stars-Mass-and-Radius-using-Asteroseismology.ipynb`.

**Comment by lglattly** [comment]
@ojhall94 and @barentsen I finished copy editing this notebook "How to Estimate a Star's Mass and Radius Using Asteroseismology" and it was in excellent shape! I made very minor copy edits throughout. This notebook is all set on my end and ready to go!

**Comment by barentsen** [comment]
Thanks @lglattly! :+1:

**Comment by barentsen** [comment]
This notebook has successfully been merged into `spacetelescope/notebooks`.  Thanks everyone!  Closing the issue...
