### ISSUE TITLE
Tutorial: Searching for Kepler/K2 and TESS data products using Lightkurve

### ISSUE THREAD

**Issue by nksaunders** [barentsen/notebooks#17]
This tutorial describes the data products available to download using `lightkurve`, and give examples of how to use the `lightkurve` search functions. 

### Learning Goals
* Understand the data products available to query and download.
* Understand how to use Lightkurve to search for Kepler/K2 and TESS data products.
* Understand how to use the MAST online portal to search for Kepler/K2 and TESS data products.

### Open questions
* What is the best way to demonstrate how to use the MAST portal?

**Comment by barentsen** [comment]
:+1:

> What is the best way to demonstrate how to use the MAST portal?

I think showing how to query MAST in a programmatic way is already ambitious enough for a tutorial!  I would leave the use of the MAST online portal to different resources, though it could be worth including a screenshot to demonstrate that anything that can be queried programmatically is also visible via the online portal.

**Comment by nksaunders** [comment]
This tutorial is ready for review!

**Comment by barentsen** [comment]
Thanks @nksaunders!  I completed a review of this notebook and found it to be in a great shape.

I believe it is ready for copy-editing.

The filename is `Searching for Kepler/K2 and TESS data products.ipynb`.

**Comment by lglattly** [comment]
@nksaunders and @barentsen I finished copy editing this notebook and it was also in great shape! I made minor copy edits throughout and switched out Trappist-1 for KIC 3733346 and K2 Campaign 12 for Kepler Quarter 2 at the end of Section 2.0 as per my conversation with @barentsen over Slack. This notebook is all set on my end and ready to go!

**Comment by barentsen** [comment]
Thanks @lglattly! :+1:

**Comment by barentsen** [comment]
This notebook has successfully been merged into `spacetelescope/notebooks`.  Thanks everyone!  Closing the issue...
