### ISSUE TITLE
Tutorial: Removing scattered light from TESS data using the Lightkurve RegressionCorrector

### ISSUE THREAD

**Issue by nksaunders** [barentsen/notebooks#18]
This is a slightly revised version of an existing lightkurve tutorial by @christinahedges:

[How to remove TESS scattered light using `RegressionCorrector`](http://docs.lightkurve.org/tutorials/04-how-to-remove-tess-scattered-light-using-regressioncorrector.html)

This tutorial would be very valuable to the community, and requires little modification to match the style guide. 

To do:
- [x] Update the code to be compatible with lightkurve v.2.0 
- [x] Modified the introduction to match style guide
- [x] Break 2 existing sections into more detailed subsections
- [x] Compare benefits of `RegressionCorrector` and `PLDCorrector`

**Comment by barentsen** [comment]
:+1:

Please make sure to include a little paragraph explaining the benefits and drawbacks of using `RegressionCorrector` directly rather than `PLDCorrector`.  I imagine the benefit is that a user can provide custom noise vectors (tho I don't think the RegressionCorrector demonstrates this yet?).  The drawback is that the user needs to do more work.  Is that right?

**Comment by nksaunders** [comment]
This notebook is now ready for review.

Note: the comparison to PLD currently looks pretty bad, but these issues will be resolved when [this PR](https://github.com/KeplerGO/lightkurve/pull/847) is merged. I've tested the correction on my own branch of lightkurve, and the PLD correction looks very similar to the RegressionCorrector version.

**Comment by barentsen** [comment]
Thanks @nksaunders. This is a great and important notebook!

I only made two significant changes:
* I changed the word `raw` into `uncorrected` across the text and variables (it's best to reserve the word `raw` for completely uncalibrated data, cf. https://github.com/KeplerGO/lightkurve/issues/708).
* I merged https://github.com/KeplerGO/lightkurve/pull/799 and re-ran the cells to get rid of the DesignMatrix rank warnings!

This notebook is ready for copy editing! :+1:

**Comment by barentsen** [comment]
The filename is `Removing scattered light from TESS data using the Lightkurve RegressionCorrector.ipynb`

**Comment by lglattly** [comment]
@nksaunders and @barentsen I finished copy editing this notebook and it was also in great shape! I made minor copy edits and formatting changes throughout. It's all set on my end and ready to go!

**Comment by barentsen** [comment]
Awesome :+1:

**Comment by barentsen** [comment]
This notebook has successfully been merged into `spacetelescope/notebooks`.  Thanks everyone!  Closing the issue...
