### ISSUE TITLE
Tutorial: How to create a river plot using Lightkurve

### ISSUE THREAD

**Issue by nksaunders** [barentsen/notebooks#21]
This notebook is adapted from the existing lightkurve tutorial: ["How to use lightkurve's river plot function"](http://docs.lightkurve.org/tutorials/03-using-river-plots.html).

It's short and sweet, and shows off a useful but little-known (to my knowledge) function in lightkurve. It didn't require much modification to bring up to date with lightkurve v2.0 or the style guide, so it's ready for review!

**Comment by barentsen** [comment]
I propose changing the title into `How to visualize periodic signals using a river plot` to make it slightly more self-explanatory, because river plots are not a widely-known term.

**Comment by barentsen** [comment]
Thanks @nksaunders! This is a great and useful tutorial. :+1:

I completed my review and believe it is ready for copy-editing.

Filename: `How to visualize periodic signals using a river plot`

**Comment by nksaunders** [comment]
@barentsen that change sounds great to me, thanks!

**Comment by lglattly** [comment]
@nksaunders and @barentsen the copy editing of this notebook is complete. I made minor edits throughout, and the notebook is all set on my end and ready to go!

**Comment by barentsen** [comment]
This notebook has successfully been merged into `spacetelescope/notebooks`.  Thanks everyone!  Closing the issue...
