### ISSUE TITLE
Tutorial: Using community-provided K2 light curves

### ISSUE THREAD

**Issue by barentsen** [barentsen/notebooks#6]
I plan to start working on the tutorial titled ***Using community-provided K2 light curves***.

Learning goals:
* Why do community-provided light curves exist?
* Which community light curves are available for K2? (EVEREST, SFF, etc...)
* How to download and use community light curves with Lightkurve?

As part of this tutorial, I expect to add a few simple functions to Lightkurve:
* `read_sff(filename)` will read in light curves generated by the K2SS pipeline (Andrew Vanderburg et al.)
* `read_everest(filename)` will read in files generated by the EVEREST pipeline (Luger et al.).
* `read_halophot(filename)` will read in files generated by the HALOPHOT pipeline (Ben Pope et al.)
* And, likely a few others!

These read functions will return a `KeplerLightCurve` object given a data product filename.  I will also look into adding download support for these products, e.g. perhaps via `search_lightcurvefile(object, hlsp=True)`.

Please post thoughts and suggestions below!

**Comment by nksaunders** [comment]
This is a great idea @barentsen! 

For the code additions, do you think each of the functions that read HLSPs should return specific subclasses of `KeplerLightCurveFile` objects (e.g. `SFFLightCurveFile`, `EverestLightCurveFile`)?  Or would it be better to read the data to conform with the current class attributes? The latter would be simpler but could limit the access to HLSP-specific data.

I'd be happy to help with developing these functions and incorporating HLSPs into the `search_lightcurvefile` interface!

**Comment by ojhall94** [comment]
This sounds great! Thinking out loud: How many commonly used community-provided K2 light curves are there? If a new method were to appear in the future, how would we make that easily compatible with Lightkurve?

**Comment by barentsen** [comment]
Thanks both for your thoughts!  I tried to answer your questions, and implement a proposed solution, here: https://github.com/KeplerGO/lightkurve/pull/739

**Comment by ojhall94** [comment]
> Thanks both for your thoughts! I tried to answer your questions, and implement a proposed solution, here: [KeplerGO/lightkurve#739](https://github.com/KeplerGO/lightkurve/pull/739)

**Comment by ojhall94** [comment]
Woops!

**Comment by barentsen** [comment]
Support for EVEREST and K2SFF has now been added: https://github.com/KeplerGO/lightkurve/pull/739

There is no draft tutorial yet however.  Help is welcome!
