### ISSUE TITLE
Tutorial: How to combine multiple Quarters of Kepler observations

### ISSUE THREAD

**Issue by ojhall94** [barentsen/notebooks#7]
This notebook will form part of the series: Getting started with *Kepler* and *K2* data products.

In this notebook, we will focus on combining multiple quarters of data into a single `LightCurve` object. This will require previous knowledge of `LightCurve` and `LightCurveFile` objects from #3. 

We can draw inspiration from existing Lightkurve tutorials:
- [How to combine light curves from different Kepler quarters](http://docs.lightkurve.org/tutorials/03-appending-lightcurves.html)

---

Learning Goals:
- What is a Kepler Quarter?
- How to download multiple Quarters of Kepler data.
- How to combine multiple Quarters of data to form a single `LightCurve` object
- What the benefits are of combining Quarters.
  - This could be through a brief use of the `.fold()` function shown in the light curve tutorial.

**Comment by ojhall94** [comment]
I've put together a draft of this notebook, ready for comments. I'm certain there's lots of great changes we can make to it!

**Comment by barentsen** [comment]
Thanks @ojhall94.  This is great!

My only real comment is that I would provide slightly more details in a few places:
* I would consider adding `Understanding a Kepler Quarter` to the learning goals, and having the first section be `1.  What is a Kepler Quarter?`.  This section could provide a few more details on
   * Why Kepler used quarters.  Perhaps show a graphic which illustrates that Kepler had to rotate every 3 months to keep its solar panels oriented to the Sun. I remember seeing a graphic somewhere, likely in one of the handbooks, which you could think about including.
   * Explain what is different quarter-to-quarter. It's useful to point out that targets falling on a different place on the detector meant that their PSF was slightly different.  This in turn caused the photometric aperture masks (and thus the fraction of flux they captured) to be slightly different.  This in turn caused the relative impact of the differential velocity aberration effect and pointing drift to be different.  None of this needs to be explained in any great detail, but I'd try to hint at these effects and link to the best Handbook/Paper section on the topic we can find.
   * Explain what is the same quarter-to-quarter (e.g. the majority of the target list remained identical).

* I would provide a few more words explaining why the unnormalized light curves look so strikingly different (predominantly: differential velocity aberration, spacecraft pointing changing, temperature-induced focus variations).  It is very well explained in Section 6 of the [Kinemuchi 2012](https://arxiv.org/pdf/1207.3093.pdf) paper.  I'd recap that paragraph in one or two sentences and then refer to the paper for details.  I think it's good to make sure the reader knows that the different systematics that affect each quarter are fairly well understood and can be read up on elsewhere.

* The text in Section 4 suggests that `stitch()` only concatenates the light curves. I'd explicitly explain that `stitch()` does what you showed in Section 3, i.e. it normalizes each quarter by the median for you.

Does that make sense?

**Comment by ojhall94** [comment]
Great suggestions, agreed on all counts! I'll get to work on them tomorrow :)

**Comment by ojhall94** [comment]
Thanks for all the feedback! Worked them into the tutorial, I think its a lot more fleshed out now. Let me know what you think!

**Comment by barentsen** [comment]
Thanks @ojhall94!  This is going in the right direction!

This tutorial will need a few changes to the code if we end up turning `LightCurve` into a sub-class of `TimeSeries`, so we'll want to revisit after a decision is made on https://github.com/KeplerGO/lightkurve/pull/744!

**Comment by ojhall94** [comment]
Good idea. In the meantime, I have a comment from Rebekah Hounsell that I think are worth discussing in a bit more detail here:

About Section 1. What is a Kepler Quarter:
> Do you want a whole text section discussing the Kepler quarters or maybe a link to a separate page?
Too much text could be overwhelming rather than informative.

**Comment by astrobel** [comment]
This a great tutorial! Everything is really cohesive, and I think the explanation of why quarters occur is useful in this case, especially since you call back to it later in the text. One thing I think could be clearer in this is that the corrections you're doing before stitching (e.g. `.normalize()`) are quite basic since this is already PDCSAP flux, and that for stitching SAP flux, there are more steps to be taken.

**Comment by ojhall94** [comment]
Thanks for your comments here & elsewhere @astrobel!

**Comment by barentsen** [comment]
I carried out a final review and believe this notebook is ready for copy editing. :+1:

**Comment by lglattly** [comment]
@ojhall94 and @barentsen I finished copy editing this tutorial "How to Combine Multiple Quarters of Kepler Data with Lightkurve" and it was in great shape, very nice clear writing!

I made some minor copy edits throughout and also combined the summary and companion content text under the Introduction section, as per our finalized tutorial template. The only thing I didn't do was touch the Additional Resources section, which we decided on our last call would be removed and additional resources would be incorporated in the main content in context (which I think is mostly happening in this tutorial with the exception of a few resources listed at the end).

So if someone can take a look at that Additional Resources section and incorporate the list of links, that would be great, otherwise this tutorial is all set on my end and ready to go!

**Comment by barentsen** [comment]
I reviewed that Additional Resources section.  I believe that all the materials that were not already linked are not immediately necessary for the tutorial (e.g. MAST TESS Webpage).  Such generic links can better be placed and kept up to date in the environment the notebooks will be integrated into.  As a result, I went ahead and removed the Additional Resources section. 

Thanks everyone!

**Comment by barentsen** [comment]
This notebook has successfully been merged into `spacetelescope/notebooks`.  Thanks everyone!  Closing the issue...
