### ISSUE TITLE
Tutorial: Using other official data products

### ISSUE THREAD

**Issue by ojhall94** [barentsen/notebooks#8]
This notebook will form part of the series: Getting started with *Kepler* and *K2* data products.

In this notebook, we will focus on using and understanding official data products other than flux.

---

Learning goals
- What data products are available?
- What are the benefits of these data?
- Learn how to access and use these data for science.

**Comment by ojhall94** [comment]
I haven't used these products before, so I welcome pointers on how auxiliary data might have been useful in other peoples science :)

**Comment by barentsen** [comment]
An overview of other official data products is available at http://archive.stsci.edu/kepler/data_products.html .  The page also provides useful literature reference.

Example use cases could include:
* Using Cotrending Basis Vectors Files to investigate systematics shared across targets.
* Using Ancillary Engineering FITS Files to access spacecraft telemetry (e.g. show that temperature correlates with PSF width).
* Using Collateral Files to access black/smear levels (useful to measure very bright stars).
* Using the SPICE kernel to obtain the Kepler spacecraft position.
* Using Kepler's PRF model.
* Plotting Kepler's Flat Field.
* Accessing high-cadence light curves obtained by the Fine Guidance Sensors.

I don't think any of these data products are particularly important for beginners, so it doesn't seem like a high priority to explain them with detailed notebooks.  However it may be fun to provide a whirlwind tour of some lesser-known data products, perhaps using 2-3 cells to show how to open and plot them.

**Comment by ojhall94** [comment]
> However it may be fun to provide a whirlwind tour of some lesser-known data products, perhaps using 2-3 cells to show how to open and plot them.

This is what I had in mind too. Awesome, thanks! I'll have a play around with the data and see if a nice format falls out.

**Comment by ojhall94** [comment]
I've been having a swing at this but finding it difficult to piece together and making very slow progress. Going to park it for now and maybe some of us can have a go at it together further down the line.

**Comment by barentsen** [comment]
It looks like we won't complete this particular tutorial before the end of the project, so I am closing the issue for now.  It was worth trying! :+1:
