### ISSUE TITLE
Tutorial: Plotting Target Pixel File Data with Lightkurve

### ISSUE THREAD

**Issue by ojhall94** [barentsen/notebooks#9]
This notebook will form part of the series: Getting started with *Kepler* and *K2* data.

At Rebekah's request, I took Tutorial #4 and split it into two tutorials. Tutorial #4 is now "Understanding Target Pixel File Products with Lightkurve", which focuses on the basics of downloading a TPF, plotting it, and understanding the metadata.

This tutorial instead focuses on plotting and understanding background file products and performing simple aperture photometry with Lightkurve's built in tools, to build a foundation for more advanced aperture photometry later on (see #2).

---
- Download and plot Target Pixel Files from the data archive using [Lightkurve](https://docs.lightkurve.org).
- Understanding the different flux data products stored in a Target Pixel File.
- Plotting the Target Pixel File Background.
- Extracting and plotting flux from a Target Pixel File.

**Comment by barentsen** [comment]
I suggest changing the titles a bit.  "Understanding Target Pixel Files" and "Using Target Pixel Files" sound very similar. How about calling this second tutorial e.g.  "Plotting Target Pixel File data with Lightkurve"?

**Comment by ojhall94** [comment]
Great suggestion!

**Comment by ojhall94** [comment]
Checked this to make sure it works in Lightkurve 2.0.

**Comment by astrobel** [comment]
I don't have many comments on this tutorial, I think it's great! Particularly like the Kepler vs TESS exercise at the end!

**Comment by barentsen** [comment]
I carried out a review and changed the occurences of `extract_aperture_photometry()` into `to_lightcurve()`.  We have only been advertising the latter in the past, so we may as well continue that to avoid confusion.

**Comment by barentsen** [comment]
I carried out a final review, made minor modifications to a few sentences, and moved the tutorial to the `ready-for-copy-editing` folder.  Thanks again @ojhall94!

**Comment by lglattly** [comment]
@ojhall94 and @barentsen I finished copy editing this tutorial "How to Plot Kepler Target Pixel File Products with Lighkurve."

As with the previous tutorial, I made small copy editing changes throughout, and I combined the information from summary and companion content under Introduction as per the tutorial template. And again, here I didn't touch the Additional Resources section, so if someone can incorporate the list of resources into the main text as needed, that would be great!

Otherwise, this tutorial is all set on my end and ready to go. Thanks!

**Comment by barentsen** [comment]
I incorporated two key links from the "Additional Resources" section into the main content by adding the following two sentences at the end of different paragaphs in Section 2:

* `Note that you can find all the details on the structure and contents of TPF files in Section 2.3.2 of the [Kepler Archive Manual](http://archive.stsci.edu/files/live/sites/mast/files/home/missions-and-data/kepler/_documents/archive_manual.pdf).`
* `You can learn more about the background removal in Section 4.2 of the [Kepler Data Processing Handbook](http://archive.stsci.edu/files/live/sites/mast/files/home/missions-and-data/kepler/_documents/KSCI-19081-002-KDPH.pdf).`

The other links did not directly contribute to the content of the tutorial, so I went ahead and removed the Additional Resources section.

I will consider this tutorial "copy editing finished" unless someone objects?

**Comment by lglattly** [comment]
The additions look good to me!

**Comment by barentsen** [comment]
This notebook has successfully been merged into `spacetelescope/notebooks`.  Thanks everyone!  Closing the issue...
